### ISSUE TITLE
GPU running out of memory while generating adversarial audios

### ISSUE THREAD

**Issue by sanchitd9** [SpeakerGuard/SpeakerGuard#4]
Hi,

I am trying to run the attackMain.py script to generate for FGSM, CW2 and CWInf attacks. But my GPU always runs out of memory:
`RuntimeError: CUDA out of memory. Tried to allocate X MiB (GPU X; X GiB total capacity; X GiB already allocated; X MiB free; X cached)`

I was using NVIDIA T4 with 16 GB memory and then upgraded to L4 with 24 GB memory but still running into the same issue. Is there a way to circumvent this?

**Comment by SpeakerGuard** [comment]
Hi, sorry for the late reply. Are you running the iv_plda model? If so, you can reduce the `-gmm_frame_bs` parameter in `attackMain.py` to slove the OOM problem.

**Comment by xueyuanZ** [comment]
Hi, 

when i tried to install libKMCUDA, some errors occured. could you help me to slove this? thanks for you a lot.

(audio_ad) (base) meigk@meigk-desktop:~/code/zxy/kmcuda-master/src$ CUDA_ARCH=6.1 pip install .
Looking in indexes: https://pypi.douban.com/simple/
Processing /home/meigk/code/zxy/kmcuda-master/src
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages (from libKMCUDA==6.2.3) (1.26.3)
Building wheels for collected packages: libKMCUDA
  Building wheel for libKMCUDA (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      running bdist_wheel
      running build
      running build_py
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/meigk/code/zxy/kmcuda-master/src/setup.py", line 85, in <module>
          setup(
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/meigk/code/zxy/kmcuda-master/src/setup.py", line 20, in run
          self._build()
        File "/home/meigk/code/zxy/kmcuda-master/src/setup.py", line 35, in _build
          check_call(("cmake", "-DCMAKE_BUILD_TYPE=Release", "-DDISABLE_R=y",
        File "/home/meigk/miniconda3/envs/audio_ad/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '('cmake', '-DCMAKE_BUILD_TYPE=Release', '-DDISABLE_R=y', '-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda/toolkit', '-DCUDA_ARCH=6.1', '.')' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for libKMCUDA
  Running setup.py clean for libKMCUDA
Failed to build libKMCUDA
ERROR: Could not build wheels for libKMCUDA, which is required to install pyproject.toml-based projects
